### ISSUE TITLE
homey mediaplayer and sonos

### ISSUE THREAD

**Issue by satbopper** [athombv/com.sonos#10]
homey 1.2.2 and 1.3.0.rc7 with latest sonos app
sonos playlists are running fine with the sonos app on my phone
in homey music i can see the sonos playlists but it runs only one song and then stops
perhaps this is the reason,i have also soundcloud playlists and with every number there is a duration of the song in minutes and seconds
the soundcloud playlists runs all the songs
in the sonos playlist there is none duration of the songs,only on the right 00
How is that possible
Further it is not possible to work with the homey media player and sonos if you have two sonos play1's
and you have configured them in pair
you can select the player but it swappes to the internal homey from which you can not play songs

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2668
