### ISSUE TITLE
Add Flow Card for Sonos to select line-in as source

### ISSUE THREAD

**Issue by djanssen1** [athombv/com.sonos#11]
What is your Homey version (Settings → System)?

1.3 RC7

What did you try to achieve?

Play Homeys voice to Sonos system using Line out connected to Line in of a Sonos Connect and automate this through Flow

What did you expect as result?

Can you please add to Sonos an extra flow card of selecting the line-in of the Sonos Connect as the source of playing.
Manually it works when you first at the Sonos app select the Line-in and then have the flow.

**Comment by djanssen1** [comment]
As a work around I currently use https://github.com/jishi/node-sonos-http-api for this running on RPI3. So based on that code you should be easily able to add this feature

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2667
