### ISSUE TITLE
text to speech

### ISSUE THREAD

**Issue by MbenzNo** [athombv/com.sonos#12]
In my Vera system I have some triggers that sends a text to speech message to my Sonos speakers. This is done by an additional plugin - VeraAlerts, but the TTS settings is configured in the Sonos app on Vera.
I would like to have a flow card to Say something trough Sonos.
I guess it will require some settings for the Sonos app to choose and configure the TTS server URL.

**Comment by djanssen1** [comment]
Hi there, I have this currently working with https://github.com/jishi/node-sonos-http-api
running on a RPI3 and using http commands through flow. You could have a look into this. It is quite flexible. Multi language.

**Comment by MbenzNo** [comment]
Good to hear, but I was hoping for a "non-programmer" solution configured in Homey alone. I dont have a RPI at the moment, and was not planning on buying one either.

**Comment by MbenzNo** [comment]
Anyone working on this?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2666
