### ISSUE TITLE
Speaker Groups

### ISSUE THREAD

**Issue by cbho** [athombv/com.sonos#14]
Hi,
Would be brilliant if you could add a feature that can group different rooms.
Although Sonos' products are not consuming a lot of power when in standby, home automation makes it possible to turn off power to them completely when leaving the house and on again when returning - however, that breaks groups that was made -  and it would be really cool if a flow could re-group different rooms when turning the system on again.
Regards,
Chr.

**Comment by leim1234** [comment]
Hi, 
I as well would really love be able to group my rooms all together, so the whole house will be playing the same music. 
hope this is possible.
greetz

**Comment by JPe2** [comment]
Grouping / Ungrouping and start playing Radio in Sonos favorites are functions that I already expected from the start.  Selection of the speakers is not working also anymore. 👎

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2664
