### ISSUE TITLE
SONOS ZP80 Shows up as Play 1

### ISSUE THREAD

**Issue by Bloke63** [athombv/com.sonos#15]
Hello developers,

In version v2.3.0 - 21.04.17 the older SONOS ZP80 which resembles the currently available in store SONOS Connect design (and is slightly smaller than the SONOS connect AMP), does show itself within the Homey GUI with a Play1 device icon.
![sonos_connect](https://user-images.githubusercontent.com/30018954/29233759-11deea24-7ef3-11e7-9da1-97956acab5c3.jpg)
![sonos homey](https://user-images.githubusercontent.com/30018954/29234215-bda02966-7ef5-11e7-902b-534efb30be97.png)

It would be nice if this icon could be corrected/added in a future release.

_**Some info from the ZP80 device in my system setup:**_
Hardwareversion: 1.1.16.3-2
WM: 0
r8: 16.0-7

If you would like me to provide more info, please let me know

Keep up the good work.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2663
