### ISSUE TITLE
[1.5.0 RC6] Sonos won't play anymore

### ISSUE THREAD

**Issue by andreasbeck** [athombv/com.sonos#16]
Using the Sonos App, I can't play any music from my favourites anymore.
This or a similar error comes up:
<img width="516" alt="bildschirmfoto 2017-08-18 um 12 41 22" src="https://user-images.githubusercontent.com/29104690/29455764-b8928f96-8412-11e7-93ed-dc9d3e539f10.png">

**Comment by smarthomecomau** [comment]
Exact same issue. Shame, this significantly reduces the functionality of Homey

**Comment by uNiiek** [comment]
Same on Homey Firmware 1.5.1
SonosAPP v2.3.0

Can't play and pause anymore.

![sonos](https://user-images.githubusercontent.com/18580351/30296018-099acd0c-9743-11e7-9052-9ced79777b2f.png)

**Comment by MarvinSchenkel** [comment]
I've got the same issue. Any update on this @BasKiers?

**Comment by fredrikhanssonsk** [comment]
Any update to this problem?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2662
