### ISSUE TITLE
Has Athom left Sonos behind?

### ISSUE THREAD

**Issue by cbho** [athombv/com.sonos#18]
Athom appears to leave the Sonos app hanging in the air - radio-wise, music providers other than Spotify/Soundcloud/Google Play, and other features missing at present...

The app is marked as "Done" on [Trello](https://trello.com/c/1hUEauD8/5-sonos) and no questions are answered there, neither at the [app store](https://apps.athom.com/app/com.sonos) - not to mention at the forum...
Issues on GitHub are pending since march 2017 - marked as "bug" or "enhancement" - but nothing happens...

At present, the app is announced with "This app adds support for Sonos devices" in the app description - but in reality, functions are rather sparse...

I know you guys are busy with a lot of new stuff coming up and stability issues on core functionalities - but is it possible at least to give a hint on the plans?
Are dreams about proper integration better forgotten?

**Comment by jeroenvollenbrock** [comment]
Hi, we're currently in the process of giving the Sonos app a huge update, however, these changes require homey version 1.5.7 to be released first. The plan is to release this sonos app update right after the release of Homey update 1.5.7 to the experimental software channel.
