### ISSUE TITLE
Sound comes from the wrong speaker when having more than one Sonos speaker.

### ISSUE THREAD

**Issue by JohanBendz** [athombv/com.sonos#19]
When I add more than one Sonos speaker to Homey I am no longer able to make music play in a specific speaker. Music rather plays from the last added speaker no matter what speaker I choose.

I guess this is a well known issue but the problem is still there months later and I can't find any information about it or solutions to it here or in the forum.

**Comment by gabbah** [comment]
Same thing here.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2660
