### ISSUE TITLE
Flow -> Using "Turn On" feature 

### ISSUE THREAD

**Issue by Schroemges** [athombv/com.sonos#24]
Would be nice not only to select start playing at a Curtain time.
I use the Playbar with the Sub combined... So if I watch tv and go to bed then the playbar remembers the last playback "TV MODE" and if i use the FLOW -> Turn On at 7:30 feature it will not start playing a Radio Station.
So it would be great if i can select the Sonos Fovorite Radio Station so it will not stick to it's TV mode

For the rest you guys doing a great job thank you

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2657
