### ISSUE TITLE
Request: isPlaying state

### ISSUE THREAD

**Issue by sossienl** [athombv/com.sonos#3]
Is there a way to actually check if Sonos is currently playing something?
To give you an idea of the use-case

When all family members (2) are leaving the house, Sonos is paused. even though it was not playing at that moment in the first case. 
When one or more family members return to the house within 30min after leaving, Sonos is set to start playing.

This works perfectly IF we were playing music in the first case, but if that is not the case then Sonos starts playing music without any particular reason ;)

**Comment by BasKiers** [comment]
Hi, I added a condition card to the app to check the playback state (playing, paused, stopped, no media). Expect this card to be added as of version 1.3.0 today or early next week.
