### ISSUE TITLE
Homey:Sonos is not aware if music was started by other tools/apps

### ISSUE THREAD

**Issue by JosStultjens** [athombv/com.sonos#6]
If we start Music on our Sonos speakers via e.g. the Sonos mobile app and not via Homey, then Homey is not aware that music is playing on any of the Sonos speakers. 
The result is that if I ask Homey to stop playing music on my Sonos speakers, it keeps on playing, because according to Homey nothing is playing, so no action is taken.

**Comment by BasKiers** [comment]
Voice commands are only working on the active speaker. Sonos can only be an active speaker in Homey music when Homey is the only one providing songs to the speaker (for now). When you select your sonos speaker as active speaker and then play something from your phone Homey will automatically switch the active speaker back to the internal speaker. When Homey then receives an pause voice command Homey will check the internal speaker to see if it is playing a song and pause that song.

**Comment by JosStultjens** [comment]
Hi Bas,

My issue is not related to voice commands.

What I meant to address is that when I look at my Sonos Play:1 device in Homey it does not show it is playing music if I started to play music on my Sonos using the Sonos app on my mobile phone.

E.g. I started to play music with the Sonos app on my mobile phone (not via Homey)

In Homey the following is shown:



If I now want Homey to stop playing music on my Sonos, I first need to tell  Homey to start playing music and then to stop playing.

Please make Homey aware of Sonos changes made outside Homey.

 

Kind regards,

Jos Stultjens

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2671
