### ISSUE TITLE
Homey: sonos is not responding to commands

### ISSUE THREAD

**Issue by fn002449** [athombv/com.sonos#7]
If I want to pauze SONOS from a flow I get an error. See image.

![schermafdruk 2017-04-12 15 10 46](https://cloud.githubusercontent.com/assets/5961917/24959299/add6da56-1f92-11e7-9323-d688a0f610d7.png)

Homey version: 1.2.0 (experimental)
SONOS app version: 2.0.3

**Comment by BasKiers** [comment]
Hi, Could you confirm this error only occurs when nothing is playing? This flow card should work when sonos is playing music

**Comment by fn002449** [comment]
If I try to play music with a flow. It doesn't give that error (its just a V), but nothing happens.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2670
