### ISSUE TITLE
Sonos SUB Icon shows as a Play 1

### ISSUE THREAD

**Issue by mruiter** [athombv/com.sonos#9]
Please add the Sonos Sub icon so this also reflects like all the other models i have.
Cosmetics counts :) And i love a correct and good looking icon

**Comment by IvoDerksen** [comment]
Yes, it is already in the repo!

<img width="760" alt="sonos_sub" src="https://user-images.githubusercontent.com/22196684/30959458-7ec96840-a440-11e7-8802-5049843aa03b.png">

[Sonos SUB SVG.zip](https://github.com/athombv/com.sonos/files/1340284/Sonos.SUB.SVG.zip)

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2669
